[environments.default]
store = "behumann.myshopify.com"
ignore = [
  "templates/*.json",
  "sections/*.json",
  "config/*.json"
]
open = true

[environments.dev]
store = "hmn-anatta-dev.myshopify.com"
theme = "193599078769"